### ISSUE TITLE
OAuth util doesn't respect body-enconding?

### ISSUE THREAD

**Issue by timkley** [raycast/utils#35]
I might be wrong but it seems like the `bodyEnconding` [property](https://github.com/raycast/utils/blob/main/src/oauth/OAuthService.ts#L22) is not respected since its not getting passed into the function calls of [fetchTokens](https://github.com/raycast/utils/blob/main/src/oauth/OAuthService.ts#L202-L207) as well as [refreshToken](https://github.com/raycast/utils/blob/main/src/oauth/OAuthService.ts#L183-L187).

I might be missing something, but I get an error from our service, which expects url-encoded params, that the content type header is wrong.

Happy to provide a PR if wanted :)

One question: what are the best practices with supporting OAuth using client secrets instead of PKCE? I'd like to connect [awork](https://developers.awork.com/authentication) which unfortunately don't support PKCE. I know its discouraged through the docs but would hope there is still a solution when storing the client secret in the users settings.

Thanks up front :)

**Comment by mathieudutour** [comment]
Ah I just fixed it before seeing your issue - it's fixed in 1.16.1

**Comment by timkley** [comment]
@mathieudutour thank you!!

If your time allows it I'd really appreciate an answer to my question above:

> One question: what are the best practices with supporting OAuth using client secrets instead of PKCE? I'd like to connect [awork](https://developers.awork.com/authentication) which unfortunately don't support PKCE. I know its discouraged through the docs but would hope there is still a solution when storing the client secret in the users settings.

Thanks up front and have a nice day!

**Comment by mathieudutour** [comment]
Right, the solution for that is to use a proxy server which will do the pkce flow while keeping the secret secure.

If you head to https://oauth.raycast.com/encrypt-form, you can enter some info about your oauth provider and get some URLs back that you can use in your extension. We haven't documented it yet because, as you can see, we haven't had time to polish it yet (but it's really secure and doesn't store your secret)

**Comment by timkley** [comment]
@mathieudutour wow, thanks! This works really great, I really appreciate the effot 👏🏻
